### ISSUE TITLE
Merge lines with same buses to one system

### ISSUE THREAD

**Issue by lukasol** [openego/osmTGmod#8]
Due to the method in osmTGmod (see figure attached), there are some lines that have the same bus0 and bus1. These occurrences should be replaced by a merger into one system with several cables (see code snippet attached as a first starter).

[grouping_ego_lines.txt](https://github.com/openego/osmTGmod/files/810927/grouping_ego_lines.txt)
![osmtgmod_abstraktion](https://cloud.githubusercontent.com/assets/17782967/23463028/6faf8804-fe90-11e6-9692-d37c63284de0.png)

**Comment by lukasol** [comment]
@ulfmueller @mariusves 
Same here. Does this require any action on the osmTGmod side?

**Comment by mariusves** [comment]
I think that this doesn't require changes on the osmTGmod side. 
I'm currently testing the grouped line model against the "as is" model to check for differences.
If there are none, the grouping could either be done in the dataprocessing script osmtgmod2pypsa.sql or as stated [here](https://github.com/openego/eTraGo/issues/17) as an in-app option directly in python.
