### ISSUE TITLE
line does not get x,r and s_nom

### ISSUE THREAD

**Issue by ulfmueller** [openego/osmTGmod#9]
in Brandenburg is a very small line which did not get the relevant x,r, and s_nom values. (in the last dp run).
it is line_id 18314
@lukasol Do you have an idea why that happens? Can you fix it?

**Comment by lukasol** [comment]
There used to be subquery that set power=transformer for very short lines. However, this was the only line affected and obviously does not make sense, so I get rid of this query. 

Do you want me to update the x,r and s_nom values in the db? I suppose 
- grid.otg_ehvhv_branch_data
- model_draft.ego_grid_pf_hv_line 

are the relevant tables or do I miss one?

**Comment by lukasol** [comment]
@ulfmueller

**Comment by ulfmueller** [comment]
> There used to be subquery that set power=transformer for very short lines.

Generally sounds reasonable. I do not understand why that leads to missing values. Anyhow, if you say to just get rid of that query solve the problem without any drawback I thank you for fixing the bug!

To update the tables in the model_draft.ego_grid_pf_hv_line probably does not make sense since a new dp run is been running?! In other words, if the dp is not at that point yet where this get relevant, I would just change the osmTGmod data and then it should be fixed right? Otherwise I would do it like suggested!

**Comment by lukasol** [comment]
I updated the data in grid.otg_ehvhv_branch_data and hope I was in time for the dp...
